CREATE TABLE memos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 
    title VARCHAR(55) NOT NULL,
 
    body TEXT NOT NULL,
 
    images TEXT ARRAY DEFAULT NULL,
 
    is_active BOOLEAN DEFAULT TRUE,

    role employee_role DEFAULT NULL,

    created_by UUID DEFAULT NULL,
    
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version INTEGER DEFAULT 0 NOT NULL
);
 