-- public.revinfo definition

-- Drop table

-- DROP TABLE revinfo;

CREATE TABLE revinfo (
	rev BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp TIMESTAMP NULL,
	username varchar(255) NULL
);