 -- public.auth_tokens_aud definition

-- Drop table

-- DROP TABLE auth_tokens_aud;

CREATE TABLE auth_tokens_aud (
	id UUID NOT NULL,
	rev BIGINT NOT NULL,
	revtype INT NOT NULL,
	expired_at TIMESTAMP NOT NULL,
	refresh_token varchar(255) NOT NULL,
	CONSTRAINT auth_tokens_aud_pkey PRIMARY KEY (rev, id)
);


-- public.auth_tokens_aud foreign keys

ALTER TABLE public.auth_tokens_aud ADD CONSTRAINT fke6gak9s0b204ojb53xdj4moyo FOREIGN KEY (rev) REFERENCES revinfo(rev);
-- query generated by DBeaver 