-- public.categories_aud definition

-- Drop table

-- DROP TABLE categories_aud;

CREATE TABLE categories_aud (
	id BIGINT NOT NULL,
	rev BIGINT NOT NULL,
	revtype INTEGER NOT NULL,
	is_active BOOLEAN NOT NULL,
	name varchar(255) NOT NULL,
	total_items BIGINT NULL,
	CONSTRAINT categories_aud_pkey PRIMARY KEY (rev, id)
);


-- public.categories_aud foreign keys

ALTER TABLE public.categories_aud ADD CONSTRAINT fk6ti58h8w0q47oacscu06hcite FOREIGN KEY (rev) REFERENCES revinfo(rev);
-- query generated by DBeaver 