-- public.customers_aud definition

-- Drop table

-- DROP TABLE customers_aud;

CREATE TABLE customers_aud (
	id UUID NOT NULL,
	rev BIGINT NOT NULL,
	revtype INTEGER NULL,
	latitude DOUBLE PRECISION NULL,
	longitude DOUBLE PRECISION NULL,
	contact varchar(255) NULL,
	email varchar(255) NULL,
	is_active BOOLEAN NULL,
	"name" varchar(255) NULL,
	shipping_address varchar(255) NULL,
	CONSTRAINT customers_aud_pkey PRIMARY KEY (rev, id)
);


-- public.customers_aud foreign keys

ALTER TABLE public.customers_aud ADD CONSTRAINT fk6yi01p88qesad1xo7fjc7qrx2 FOREIGN KEY (rev) REFERENCES revinfo(rev);
-- query generated by DBeaver 