-- public.employees_aud definition

-- Drop table

-- DROP TABLE employees_aud;

CREATE TABLE employees_aud (
	id UUID NOT NULL,
	rev BIGINT NOT NULL,
	revtype INTEGER NULL,
	fullname varchar(255) NULL,
	is_active BOOLEAN NULL,
	last_device varchar(255) NULL,
	last_ip varchar(255) NULL,
	"role" varchar(255) NULL,
	username varchar(55) NULL,
	CONSTRAINT employees_aud_pkey PRIMARY KEY (rev, id),
	CONSTRAINT employees_aud_role_check CHECK (((role)::text = ANY ((ARRAY['CASHIER'::character varying, 'FINANCE'::character varying, 'WAREHOUSE'::character varying, 'OWNER'::character varying])::text[])))
);


-- public.employees_aud foreign keys

ALTER TABLE public.employees_aud ADD CONSTRAINT fk4lmhklnmephpbpt5uow5pikga FOREIGN KEY (rev) REFERENCES revinfo(rev);
-- query generated by DBeaver 