-- public.memo_views_aud definition

-- Drop table

-- DROP TABLE memo_views_aud;

CREATE TABLE memo_views_aud (
	id varchar(255) NOT NULL,
	rev BIGINT NOT NULL,
	revtype INTEGER NULL,
	memo_id BIGINT NULL,
	CONSTRAINT memo_views_aud_pkey PRIMARY KEY (rev, id)
);


-- public.memo_views_aud foreign keys

ALTER TABLE public.memo_views_aud ADD CONSTRAINT fkk4alivwmyh6q0tx56fipexcnc FOREIGN KEY (rev) REFERENCES revinfo(rev);
-- query generated by DBeaver 