-- public.memos_aud definition

-- Drop table

-- DROP TABLE memos_aud;

CREATE TABLE memos_aud (
	id BIGINT NOT NULL,
	rev BIGINT NOT NULL,
	revtype INTEGER NULL,
	body varchar(255) NULL,
	images _varchar NULL,
	is_active BOOLEAN NULL,
	"role" varchar(255) NULL,
	title varchar(55) NULL,
	CONSTRAINT memos_aud_pkey PRIMARY KEY (rev, id),
	CONSTRAINT memos_aud_role_check CHECK (((role)::text = ANY ((ARRAY['CASHIER'::character varying, 'FINANCE'::character varying, 'WAREHOUSE'::character varying, 'OWNER'::character varying])::text[])))
);


-- public.memos_aud foreign keys

ALTER TABLE public.memos_aud ADD CONSTRAINT fko0wbr5t1iy9r6oxmf5fofl29p FOREIGN KEY (rev) REFERENCES revinfo(rev);
-- query generated by DBeaver 