-- public.products_aud definition

-- Drop table

-- DROP TABLE products_aud;

CREATE TABLE products_aud (
	id BIGINT NOT NULL,
	rev BIGINT NOT NULL,
	revtype INTEGER NULL,
	base_price BIGINT NULL,
	is_active BOOLEAN NULL,
	"name" varchar(255) NULL,
	sell_price BIGINT NULL,
	stock_minimum BIGINT NULL,
	stock_quantity BIGINT NULL,
	CONSTRAINT products_aud_pkey PRIMARY KEY (rev, id)
);


-- public.products_aud foreign keys

ALTER TABLE public.products_aud ADD CONSTRAINT fkis5p0x6t8gvib9m5ra1fiybi3 FOREIGN KEY (rev) REFERENCES revinfo(rev);
-- query generated by DBeaver 