-- public.suppliers_aud definition

-- Drop table

-- DROP TABLE suppliers_aud;

CREATE TABLE suppliers_aud (
	id UUID NOT NULL,
	rev BIGINT NOT NULL,
	revtype INTEGER NULL,
	contact varchar(255) NULL,
	email varchar(255) NULL,
	is_active BOOLEAN NULL,
	"name" varchar(255) NULL,
	CONSTRAINT suppliers_aud_pkey PRIMARY KEY (rev, id)
);


-- public.suppliers_aud foreign keys

ALTER TABLE public.suppliers_aud ADD CONSTRAINT fk72bois07oflhic0klfap83rlh FOREIGN KEY (rev) REFERENCES revinfo(rev);
-- query generated by DBeaver 