-- public.supplies_aud definition

-- Drop table

-- DROP TABLE supplies_aud;

CREATE TABLE supplies_aud (
	id UUID NOT NULL,
	rev BIGINT NOT NULL,
	revtype INTEGER NULL,
	description varchar(255) NULL,
	invoice_id varchar(55) NULL,
	status varchar(255) NULL,
	CONSTRAINT supplies_aud_pkey PRIMARY KEY (rev, id),
	CONSTRAINT supplies_aud_status_check CHECK (((status)::text = ANY ((ARRAY['UNPAID'::character varying, 'COMPLETE'::character varying, 'CANCELLED'::character varying])::text[])))
);


-- public.supplies_aud foreign keys

ALTER TABLE public.supplies_aud ADD CONSTRAINT fks5m1ucbr81wvp7kxywn0l95o2 FOREIGN KEY (rev) REFERENCES revinfo(rev);
-- query generated by DBeaver 