-- public.supply_items_aud definition

-- Drop table

-- DROP TABLE supply_items_aud;

CREATE TABLE supply_items_aud (
	id UUID NOT NULL,
	rev BIGINT NOT NULL,
	revtype INTEGER NULL,
	description varchar(255) NULL,
	price BIGINT NULL,
	quantity BIGINT NULL,
	CONSTRAINT supply_items_aud_pkey PRIMARY KEY (rev, id)
);


-- public.supply_items_aud foreign keys

ALTER TABLE public.supply_items_aud ADD CONSTRAINT fkk6kht3bre9tdm0o3ykq9lowe4 FOREIGN KEY (rev) REFERENCES revinfo(rev);
-- query generated by DBeaver 