-- public.supply_payments_aud definition

-- Drop table

-- DROP TABLE supply_payments_aud;

CREATE TABLE supply_payments_aud (
	id UUID NOT NULL,
	rev BIGINT NOT NULL,
	revtype INTEGER NULL,
	is_for_refund BOOLEAN NULL,
	payment_from varchar(255) NULL,
	payment_to varchar(255) NULL,
	total_payment BIGINT NULL,
	CONSTRAINT supply_payments_aud_pkey PRIMARY KEY (rev, id)
);


-- public.supply_payments_aud foreign keys

ALTER TABLE public.supply_payments_aud ADD CONSTRAINT fktcfj4telagoykwfoynwyp41of FOREIGN KEY (rev) REFERENCES revinfo(rev);
-- query generated by DBeaver 