-- public.transactions_aud definition

-- Drop table

-- DROP TABLE transactions_aud;

CREATE TABLE transactions_aud (
	id UUID NOT NULL,
	rev BIGINT NOT NULL,
	revtype INTEGER NULL,
	invoice_id varchar(55) NULL,
	status varchar(255) NULL,
	CONSTRAINT transactions_aud_pkey PRIMARY KEY (rev, id),
	CONSTRAINT transactions_aud_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESS'::character varying, 'COMPLETE'::character varying, 'CANCELLED'::character varying])::text[])))
);


-- public.transactions_aud foreign keys

ALTER TABLE public.transactions_aud ADD CONSTRAINT fks0a2j7849lgmcshqip6rcp7kx FOREIGN KEY (rev) REFERENCES revinfo(rev);
-- query generated by DBeaver 