-- public.transaction_items_aud definition

-- Drop table

-- DROP TABLE transaction_items_aud;

CREATE TABLE transaction_items_aud (
	id UUID NOT NULL,
	rev BIGINT NOT NULL,
	revtype INTEGER NULL,
	description varchar(255) NULL,
	price BIGINT NULL,
	quantity BIGINT NULL,
	CONSTRAINT transaction_items_aud_pkey PRIMARY KEY (rev, id)
);


-- public.transaction_items_aud foreign keys

ALTER TABLE public.transaction_items_aud ADD CONSTRAINT fkelm6kubr77uyd9uvh412iys7g FOREIGN KEY (rev) REFERENCES revinfo(rev);
-- query generated by DBeaver 