-- public.transaction_payments_aud definition

-- Drop table

-- DROP TABLE transaction_payments_aud;

CREATE TABLE transaction_payments_aud (
	id UUID NOT NULL,
	rev BIGINT NOT NULL,
	revtype INTEGER NULL,
	is_for_refund BOOLEAN NULL,
	payment_from varchar(255) NULL,
	payment_to varchar(255) NULL,
	total_payment BIGINT NULL,
	CONSTRAINT transaction_payments_aud_pkey PRIMARY KEY (rev, id)
);


-- public.transaction_payments_aud foreign keys

ALTER TABLE public.transaction_payments_aud ADD CONSTRAINT fkok24nyrxa7u12437fq685m00f FOREIGN KEY (rev) REFERENCES revinfo(rev);
-- query generated by DBeaver 