ALTER TABLE auth_tokens ADD COLUMN created_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM', ADD COLUMN updated_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM';
ALTER TABLE categories ADD COLUMN created_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM', ADD COLUMN updated_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM';
ALTER TABLE customers ADD COLUMN created_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM', ADD COLUMN updated_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM';
ALTER TABLE employees ADD COLUMN created_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM', ADD COLUMN updated_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM';
ALTER TABLE memos ADD COLUMN created_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM', ADD COLUMN updated_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM';
ALTER TABLE memo_views ADD COLUMN created_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM', ADD COLUMN updated_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM';
ALTER TABLE products ADD COLUMN created_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM', ADD COLUMN updated_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM';
ALTER TABLE stock_cards ADD COLUMN created_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM', ADD COLUMN updated_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM';
ALTER TABLE suppliers ADD COLUMN created_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM', ADD COLUMN updated_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM';
ALTER TABLE supplies ADD COLUMN created_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM', ADD COLUMN updated_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM';
ALTER TABLE supply_items ADD COLUMN created_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM', ADD COLUMN updated_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM';
ALTER TABLE supply_payments ADD COLUMN created_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM', ADD COLUMN updated_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM';
ALTER TABLE transactions ADD COLUMN created_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM', ADD COLUMN updated_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM';
ALTER TABLE transaction_items ADD COLUMN created_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM', ADD COLUMN updated_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM';
ALTER TABLE transaction_payments ADD COLUMN created_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM', ADD COLUMN updated_by VARCHAR(55) NOT NULL DEFAULT 'SYSTEM';


